"""
features.py
===========
Feast feature definitions for the Stock Movement Predictor.

Entities:
    stock           — keyed by stock_name (string)

Feature Views:
    stock_features  — rolling_avg_10, volume_sum_10 per stock per minute
"""

from datetime import timedelta
from pathlib import Path

from feast import (
    Entity,
    FeatureView,
    Field,
    FileSource,
    ValueType,
)
from feast.types import Float64, String


# ─── Entity ────────────────────────────────────────────────────────────────────

stock = Entity(
    name="stock_name",
    value_type=ValueType.STRING,
    description="NSE stock ticker symbol",
)


# ─── Data Sources ──────────────────────────────────────────────────────────────
# The parquet file is generated by feast_materialize.py before `feast apply`.

_PARQUET_PATH = str(
    (Path(__file__).parent / "data" / "stock_features.parquet").resolve()
)

stock_source = FileSource(
    name="stock_features_source",
    path=_PARQUET_PATH,
    timestamp_field="event_timestamp",
)


# ─── Feature Views ─────────────────────────────────────────────────────────────

stock_features = FeatureView(
    name="stock_features",
    entities=[stock],
    ttl=timedelta(days=1825),        # 5 years — covers full dataset window
    schema=[
        Field(name="rolling_avg_10", dtype=Float64),
        Field(name="volume_sum_10",  dtype=Float64),
    ],
    source=stock_source,
    online=True,
)
